;;; init-packages.el --- Package declarations for elpaca  -*- lexical-binding: t -*-
;;; Run `emacs --sync` or M-x elpaca-sync to install/update packages.

(elpaca `(,@elpaca-order))
(elpaca symbol-overlay)
(elpaca page-break-lines)
(elpaca (transient :host github :repo "magit/transient"))
(elpaca (telega :type git :host github :branch "master"))
(elpaca gptel)
(elpaca yasnippet)
(elpaca ws-butler)
(elpaca magit)
(elpaca hl-todo)
(elpaca minions)
(elpaca persp-mode)
(elpaca (vertico :files (:defaults "extensions/*")))
(elpaca marginalia)
(elpaca orderless)
(elpaca consult)
(elpaca (racket-mode :files ("*")))
(elpaca puni)
(elpaca company)
(elpaca posframe)
(elpaca ace-window)
(elpaca avy)
(elpaca haskell-mode)
(elpaca proof-general)
(elpaca company-coq)
(elpaca paredit)
(elpaca (rime :host github :repo "DogLooksGood/emacs-rime" :files ("*.el" "Makefile" "lib.c")))
(elpaca sly)
(elpaca sly-asdf)
(elpaca sly-quicklisp)
(elpaca (sly-stepper :host github :repo "joaotavora/sly-stepper" :files (:defaults "*.el" "*.lisp" "*.asd")))
(elpaca sly-macrostep)
(elpaca geiser)
;; (elpaca geiser-guile)
(elpaca geiser-chez)
(elpaca clojure-mode)
(elpaca cider)
(elpaca fold-this)
(elpaca rg)
(elpaca lua-mode)
(elpaca go-mode)
(elpaca dockerfile-mode)
(elpaca ccls)
(elpaca lsp-mode)
(elpaca meow)
(elpaca flycheck)

(provide 'init-packages)
