;;; -*- lexical-binding: t -*-
;;
;; Package installation is separated from normal startup.
;; - Normal startup: loads packages from elpaca builds directory only.
;; - Sync mode: `emacs --sync` or `M-x elpaca-sync' to install/update.

(defvar elpaca-installer-version 0.12)
(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-sources-directory (expand-file-name "sources/" elpaca-directory))
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                              :ref nil :depth 1 :inherit ignore
                              :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                              :build (:not elpaca-activate)))

(defvar elpaca-sync-mode (member "--sync" command-line-args)
  "Non-nil when Emacs was started with --sync to install/update packages.")
(setq command-line-args (delete "--sync" command-line-args))

(defvar elpaca-cache-file (expand-file-name "elpaca/cache.el" user-emacs-directory)
  "Cached load-path and autoloads generated by `emacs --sync'.")

(defun elpaca--generate-cache ()
  "Generate a single cache file with all load-paths and autoloads."
  (let ((entries '()))
    (dolist (dir (directory-files elpaca-builds-directory t "\\`[^.]"))
      (when (file-directory-p dir)
        (push (format "(add-to-list 'load-path %S)" dir) entries)
        (let ((autoloads (expand-file-name
                          (concat (file-name-nondirectory dir) "-autoloads.el")
                          dir)))
          (when (file-exists-p autoloads)
            (push (format "(load %S nil t)" (file-name-sans-extension autoloads))
                  entries)))))
    (with-temp-file elpaca-cache-file
      (insert ";;; elpaca cache - generated by `emacs --sync', do not edit\n")
      (insert (mapconcat #'identity (nreverse entries) "\n") "\n"))
    (byte-compile-file elpaca-cache-file)))

(if elpaca-sync-mode
    ;; Sync mode: bootstrap elpaca fully and process package declarations
    (progn
      (let* ((repo  (expand-file-name "elpaca/" elpaca-sources-directory))
             (build (expand-file-name "elpaca/" elpaca-builds-directory))
             (order (cdr elpaca-order))
             (default-directory repo))
        (add-to-list 'load-path (if (file-exists-p build) build repo))
        (unless (file-exists-p repo)
          (make-directory repo t)
          (when (<= emacs-major-version 28) (require 'subr-x))
          (condition-case-unless-debug err
              (if-let* ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                        ((zerop (apply #'call-process `("git" nil ,buffer t "clone"
                                                        ,@(when-let* ((depth (plist-get order :depth)))
                                                            (list (format "--depth=%d" depth) "--no-single-branch"))
                                                        ,(plist-get order :repo) ,repo))))
                        ((zerop (call-process "git" nil buffer t "checkout"
                                              (or (plist-get order :ref) "--"))))
                        (emacs (concat invocation-directory invocation-name))
                        ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                              "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                        ((require 'elpaca))
                        ((elpaca-generate-autoloads "elpaca" repo)))
                  (progn (message "%s" (buffer-string)) (kill-buffer buffer))
                (error "%s" (with-current-buffer buffer (buffer-string))))
            ((error) (warn "%s" err) (delete-directory repo 'recursive))))
        (unless (require 'elpaca-autoloads nil t)
          (require 'elpaca)
          (elpaca-generate-autoloads "elpaca" repo)
          (let ((load-source-file-function nil)) (load "./elpaca-autoloads"))))
      (add-hook 'after-init-hook #'elpaca-process-queues)
      (require 'init-packages)
      (elpaca-wait)
      (elpaca--generate-cache)
      (message "Elpaca sync complete. Cache generated."))

  ;; Normal mode: load the single cached file
  (if (file-exists-p (concat elpaca-cache-file "c"))
      (load (file-name-sans-extension elpaca-cache-file) nil t)
    (if (file-exists-p elpaca-cache-file)
        (load (file-name-sans-extension elpaca-cache-file) nil t)
      (message "No elpaca cache found. Run `emacs --sync' to install packages."))))

(defun elpaca-sync ()
  "Sync packages by restarting Emacs in sync mode."
  (interactive)
  (let ((args (list (concat invocation-directory invocation-name)
                    "--sync")))
    (message "Running: %s" (string-join args " "))
    (apply #'start-process "elpaca-sync" "*elpaca-sync*" args)
    (switch-to-buffer "*elpaca-sync*")))

;; Package configuration (loaded in both modes)
(add-hook 'after-init-hook
          (lambda ()
            (require 'yasnippet)
            (yas-global-mode)))

(setq ws-butler-keep-whitespace-before-point nil)
(add-hook 'prog-mode-hook #'ws-butler-mode)

(add-hook 'after-init-hook
          (lambda ()
            (require 'persp-mode)
            (set-persp-parameter 'dont-save-to-file t nil)
            (setq-default persp-auto-save-opt 0)
            (persp-mode +1)))

(autoload 'ace-window "ace-window" nil t)
(keymap-set global-map "C-x C-o" #'ace-window)
(with-eval-after-load "ace-window"
  (setq aw-keys '(?a ?s ?d ?f ?g ?h ?j ?k ?l)
        aw-dispatch-alist
        '((?x aw-delete-window "Delete Window")
          (?m aw-swap-window "Swap Windows")
          (?M aw-move-window "Move Window")
          (?c aw-copy-window "Copy Window")
          (?n aw-switch-buffer-in-window "Select Buffer")
          (?u aw-switch-buffer-other-window "Switch Buffer Other Window")
          (?w aw-split-window-fair "Split Fair Window")
          (?v aw-split-window-vert "Split Vert Window")
          (?b aw-split-window-horz "Split Horz Window")
          (?o delete-other-windows "Delete Other Windows")
          (?? aw-show-dispatch-help))))

(with-eval-after-load "magit"
  (defun magit-log-dangling ()
    (interactive)
    (magit-log-setup-buffer
     (-filter
      (lambda (x) (not (or (equal "" x) (s-match "error" x))))
      (s-lines
       (shell-command-to-string
        "git fsck --no-reflogs | awk '/dangling commit/ {print $3}'")))
     '("--no-walk" "--color" "--decorate" "--follow")' nil))

  (transient-append-suffix 'magit-log "s"
    '("d" "dangling" magit-log-dangling))

  (transient-define-argument magit:--signoff ()
    :description "Add Signed-off-by trailer"
    :class 'transient-switch
    :key "/s"
    :shortarg "-s"
    :argument "--signoff"
    :level 4))

(provide 'init-package)
